title: Suci's Git space
author: Suci
email: telefonosuci@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  In Okinawa, programming, very serious business! [Miyagi]
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  # sass_dir: _sass
  load_paths:
      - _sass
      - node_modules

include:
  - _includes
  - _authors
  - _data
  - _draft
  - _layouts

suci:
  name: Enrico Succhielli
  disqus_shortname: telefonosuci
  tagline: Pixel maniac web Developer
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  cookie_notification: false
  navigation:
    - name: About Me
      url: about
    - name: Some Posts
      url: posts
  # generate social links in footer
  social_links:
    twitter: enricolebanane
    github:  telefonosuci
    linkedIn: in/enrico-succhielli
    rss: rss
    # dribbble: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # facebook: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# Build settings
#theme: suci

plugins:
  - jekyll-seo-tag
  - jekyll-multiple-languages-plugin
  - jekyll-redirect-from
#  - jekyll-feed

# The first item of languages will be used as the default.
lang: en
languages: ["en", "it"]
