title: Devsuci
author: Suci San
email: telefonosuci@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Develop is not joke, in Okinawa.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Enrico Succhielli
  tagline: Dev
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content

  # generate social links in footer
  social_links:
    twitter: enricolebanane
    github:  telefonosuci
    linkedIn: in/enrico-succhielli
    rss: rss
    # dribbble: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # facebook: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
#theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
