title: Suci's Git space
author: Suci
email: telefonosuci@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  In Okinawa, programming, very serious business! [Miyagi]
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Enrico Succhielli
  tagline: Pixel maniac web Developer
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  navigation: 
    - name: contact
      url: contact
    - name: about
      url: about
  
  # generate social links in footer
  social_links:
    twitter: enricolebanane
    github:  telefonosuci
    linkedIn: in/enrico-succhielli
    rss: rss
    # dribbble: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # facebook: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com


# Build settings
#theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
